### ISSUE TITLE
Sign up page not working

### ISSUE THREAD

**Issue by SlumberDemon** [AyushSehrawat/confess#6]
When I try to sign up I get: {"detail":"Not Found"}

Also I think that a website about sharing thoughts anonymously shouldn't have a sign in requirement ¯\_(ツ)_/¯

**Comment by AyushSehrawat** [comment]
This is work in progress ( also kinda unmaintained, you can check the last commit date)

Regarding the sign in request, it's just for a person so that he can see what are his posts ( also edit nd comment). For other users he will be `anonymous` only.

**Comment by SlumberDemon** [comment]
Okay
